server:
  port: 8081
spring:
  application:
    name: lab10-Auction
  mvc:
    problemdetails:
      enabled: true
  profiles:
    active:
      - db
  datasource:
    url: jdbc:postgresql://localhost:5601/auctiondb
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create